[package]
name = "plojyon_urnik_rewrite"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-governor = "0.8.0"
actix-web = "4.11.0"
regex = "1.11.1"
serde = "1.0.219"
serde_derive = "1.0.219"
serde_json = "1.0.141"
soup = "0.5.1"
ureq = "3.0.12"
